name: fake_love_detector
description: Romance scam detection desktop overlay app.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  screen_capturer: ^0.2.2
  window_manager: ^0.3.8
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  riverpod_annotation: ^2.3.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
